# G_REL_CURR_DIR doesn't need to be updated here since it's relative to the
# this directory "src"
default:
	$(MAKE) -C engine
	$(MAKE) -C game

clean:
	$(MAKE) -C engine clean
	$(MAKE) -C game clean

